### ISSUE TITLE
Game freeze with ice and fire amphithere mobs 

### ISSUE THREAD

**Issue by agr21** [someaddons/performant_issues#107]
1.16.4, latest performant and iaf. whenever im out of chunk, performant keep sending this error message, and freezes the game. every ai improvement set false already.
[15Feb2021 00:55:17.007] [Server thread/WARN] [com.performant.coremod.Performant/]: Trying to load chunk at blockpos X:-864 Z:560
java.lang.Exception: Chunk load debug
	at net.minecraft.world.server.ServerChunkProvider.handler$zjb000$onChunkLoadDebug(ServerChunkProvider.java:603) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217233_c(ServerChunkProvider.java:214) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:129) ~[?:?]
	at net.minecraft.world.World.func_217353_a(World.java:167) ~[?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) ~[?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:163) ~[?:?]
	at net.minecraft.world.World.func_180495_p(World.java:379) ~[?:?]
	at net.minecraft.world.IBlockReader.lambda$rayTraceBlocks$0(IBlockReader.java:46) ~[?:?]
	at net.minecraft.world.IBlockReader.func_217300_a(IBlockReader.java:142) ~[?:?]
	at net.minecraft.world.IBlockReader.func_217299_a(IBlockReader.java:45) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70685_l(LivingEntity.java:2620) ~[?:?]
	at net.minecraft.entity.ai.EntitySenses.func_75522_a(SourceFile:32) ~[?:?]
	at net.minecraft.entity.EntityPredicate.func_221015_a(SourceFile:96) ~[?:?]
	at net.minecraft.entity.ai.goal.TargetGoal.func_220777_a(SourceFile:104) ~[?:?]
	at net.minecraft.entity.ai.goal.OwnerHurtTargetGoal.func_75250_a(SourceFile:32) ~[?:?]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?]
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:349) ~[performant:1.16.2-4-3.30m]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:973) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.EntityAmphithere.func_70636_d(EntityAmphithere.java:363) ~[iceandfire:2.1.5-1.16.4]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.EntityAmphithere.func_70071_h_(EntityAmphithere.java:653) ~[iceandfire:2.1.5-1.16.4]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by someaddons** [comment]
Performant doesnt freeze the game, those logs are debug messages to help you find potential error sources. In this case it tells you that an entity is loading a chunk through accessing it, if many of those debug messages appear after eachother then something is loading a ton of chunks in a row, efffectively stalling your game. You can disable performants debug messages in the config, if I recall they are normally off by default aswell. Next time fill in the template, its important.

**Comment by agr21** [comment]
it does not happen without performant. and i get these debug messages in the exact time of the problem, nothing else.
