### ISSUE TITLE
Server errors on shutdown with disableConfigReload enabled

### ISSUE THREAD

**Issue by MarioSMB** [someaddons/performant_issues#123]
With that option set to true, shutting down the server produces errors pointing at various other mods with messages like this:  

```
[31Mar2021 16:37:48.622] [Server thread/ERROR] [net.minecraftforge.fml.config.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/whisperwoods-server.toml from tracker!
java.lang.NullPointerException: null
	at com.electronwill.nightconfig.core.file.FileWatcher.removeWatch(FileWatcher.java:134) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.unload(ConfigFileTypeHandler.java:76) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:114) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$unloadConfigs$2(ConfigTracker.java:88) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:88) ~[forge:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:135) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:682) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

It can also frequently cause the server to stall indefinitely while stopping.

**Comment by someaddons** [comment]
ye thats normal when you disable the config reload watching

**Comment by MarioSMB** [comment]
In that case I'd recommend putting a bit more information into the description of the setting - it implies disabling it will help with server performance, and the errors it causes are red herrings pointing at other mods.
