### ISSUE TITLE
Serene season warns

### ISSUE THREAD

**Issue by XionioXMaster** [someaddons/performant_issues#209]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. Install serene season and start server

** Mod version **
3.79m

** Logs **
https://gist.github.com/XionioXMaster/843a00a7c32efeb0ea3b93bce073db64 1 line wath?

[09:12:28][modloading-worker-2][WARN]: Mixin apply failed performant.mixins.json:world.chunk.ChunkManagerMixin -> net.minecraft.world.server.ChunkManager: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method func_223172_f in performant.mixins.json:world.chunk.ChunkManagerMixin cannot reduce visibiliy of PUBLIC target methodorg.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_223172_f in performant.mixins.json:world.chunk.ChunkManagerMixin cannot reduce visibiliy of PUBLIC target methodat org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:485) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:458) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:419) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:349) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]at java.lang.Class.getDeclaredMethod(Class.java:2473) ~[?:?]at net.minecraftforge.eventbus.EventBus.getDeclMethod(EventBus.java:83) ~[eventbus-4.0.0.jar:?]at net.minecraftforge.eventbus.EventBus.lambda$null$4(EventBus.java:95) ~[eventbus-4.0.0.jar:?]at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1642) ~[?:?]at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:97) ~[eventbus-4.0.0.jar:?]at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?]at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?]at sereneseasons.init.ModHandlers.init(ModHandlers.java:40) ~[sereneseasons:1.16.5-4.0.1.122]at sereneseasons.core.SereneSeasons.<init>(SereneSeasons.java:35) ~[sereneseasons:1.16.5-4.0.1.122]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]at java.lang.Class.newInstance(Class.java:584) ~[?:?]at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2]at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]

**Comment by someaddons** [comment]
fixed on 3.80m
