### ISSUE TITLE
Error during entity move

### ISSUE THREAD

**Issue by Dev4lexG** [someaddons/performant_issues#222]
**Mod version**: performant-1.16.2-5-3.83m.jar
**Platform**: Server ||Mohist Software||

**Logs**:
```
WARN]: Error during entity move:
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method) ~[?:?]
at com.performant.coremod.entity.threading.MoveThread.run(MoveThread.java:51) [performant:1.16.2-5-3.83m]
[07:31:22 WARN]: Error during entity move:
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method) ~[?:?]
at com.performant.coremod.entity.threading.MoveThread.run(MoveThread.java:51) [performant:1.16.2-5-3.83m]
[07:31:22 WARN]: Error during entity move:
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method) ~[?:?]
at com.performant.coremod.entity.threading.MoveThread.run(MoveThread.java:51) [performant:1.16.2-5-3.83m]
[07:31:22 WARN]: Error during action:
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method) ~[?:?]
at com.performant.coremod.entity.threading.ActionThread.run(ActionThread.java:44) [performant:1.16.2-5-3.83m]
[07:31:22 WARN]: Error during entity move:
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method) [?:?]
at com.performant.coremod.entity.threading.MoveThread.run(MoveThread.java:51) [performant:1.16.2-5-3.83m]
container@pterodactyl Server marked as offline...
```

**Comment by someaddons** [comment]
Mohist is not supported, it contains serveral mod-breaking incompatible changes to vanilla

**Comment by Dev4lexG** [comment]
I think what this isnt a error from the software, in the error logs doesn´t appears any class from minecraft, only from Java and performant.

If it is a error from the software, i think what appears some minecraft classes on the error

**Comment by Dev4lexG** [comment]
> Mohist is not supported, it contains serveral mod-breaking incompatible changes to vanilla

i want your reply for understant why it isn't a performant issues

**Comment by E-daw** [comment]
What is mohist?
