### ISSUE TITLE
Unable to start 1.12.2 [Bug]: 

### ISSUE THREAD

**Issue by cajlo** [someaddons/performant_issues#281]
### Describe the bug you're experiencing

Game just refuses to appear, but java process is still remaining

All I got in console is:
```
[03:35:07]` [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
java.lang.ClassNotFoundException: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ClassInfo$FrameData.<init>(ILorg/objectweb/asm/tree/FrameNode;I)V
	at org.spongepowered.asm.mixin.transformer.ClassInfo$Method.gatherFrames(ClassInfo.java:532) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo$Method.<init>(ClassInfo.java:504) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.addMethod(ClassInfo.java:917) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.<init>(ClassInfo.java:851) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.fromClassNode(ClassInfo.java:2001) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:252) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:246) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:859) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:444) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[API_!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[API_!mixinbooter-8.3.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
```

And that:

```
[03:35:11] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchFieldError: field_186802_b
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:37) ~[fo.class:?]
	at net.minecraft.item.Item.func_185043_a(Item.java:147) ~[ain.class:?]
	at net.minecraft.item.Item.<init>(Item.java:170) ~[ain.class:?]
	at net.minecraft.item.ItemAir.<init>(SourceFile:12) ~[agt.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:1225) ~[ain.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:502) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[03:35:11] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
[latest.log](https://github.com/someaddons/performant_issues/files/12271012/latest.log)

Mods I tried use it with:
```
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 506743544 bytes (483 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 LoliASM 5.14 Powered by Forge 14.23.5.2860 107 mods loaded, 107 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                        | Version            | Source                                                                                | Signature                                |
       |:------ |:------------------------- |:------------------ |:------------------------------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                 | 1.12.2             | minecraft.jar                                                                         | None                                     |
       | LCHIJA | mcp                       | 9.42               | minecraft.jar                                                                         | None                                     |
       | LCHIJA | FML                       | 8.0.99.99          | forge-1.12.2-14.23.5.2860.jar                                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                     | 14.23.5.2860       | forge-1.12.2-14.23.5.2860.jar                                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy         | 1.0.0              | minecraft.jar                                                                         | None                                     |
       | LCHIJA | itemphysic                | 1.4.0              | minecraft.jar                                                                         | None                                     |
       | LCHIJA | mixinbooter               | 8.3                | minecraft.jar                                                                         | None                                     |
       | LCHIJA | rpintegration             | 1.12.2-1.5.1.0     | BUGFIX_ADDON_-randompatches-_rpintegration-1.12.2-1.5.1.0.jar                         | None                                     |
       | LCHIJA | ClientFixer               | 1.12.2-1.9         | minecraft.jar                                                                         | None                                     |
       | LCHIJA | foamfixcore               | 7.7.4              | minecraft.jar                                                                         | None                                     |
       | LCHIJA | botania_tweaks_core       | -100               | minecraft.jar                                                                         | None                                     |
       | LCHIJA | randompatches             | 1.12.2-1.22.1.10   | BUGFIX_randompatches-1.12.2-1.22.1.10.jar                                             | None                                     |
       | LCHIJA | crafttweaker              | 4.1.20             | UTILITY_CraftTweaker2-1.12-4.1.20.674.jar                                             | None                                     |
       | LCHIJA | jei                       | 4.16.1.1003        | UTILITY_JEI_1.12.2-4.16.1.1003.jar                                                    | None                                     |
       | LCHIJA | quark                     | r1.6-179           | UTILITY_Quark-r1.6-179--API_AutoRegLib.jar                                            | None                                     |
       | LCHIJA | autoreglib                | 1.3-32             | API_AutoRegLib-1.3-32.jar                                                             | None                                     |
       | LCHIJA | codechickenlib            | 3.2.3.358          | API_CodeChickenLib-1.12.2-3.2.3.358-universal.jar                                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | collective                | 3.0                | API_collective-1.12.2-3.0.jar                                                         | None                                     |
       | LCHIJA | creativecore              | 1.10.0             | API_CreativeCore_v1.10.70_mc1.12.2.jar                                                | None                                     |
       | LCHIJA | fluidlogged_api           | 2.2.5              | API_Fluidlogged-API-v2.2.5-mc1.12.2.jar                                               | None                                     |
       | LCHIJA | gottschcore               | 1.15.0             | API_GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0.jar                                    | None                                     |
       | LCHIJA | hammercore                | 2.0.6.32           | API_HammerLib-1.12.2-2.0.6.32.jar                                                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | placebo                   | 1.6.0              | API_Placebo-1.12.2-1.6.1.jar                                                          | None                                     |
       | LCHIJA | primallib                 | {@version}         | API_primallib-v1.1.60-mc1.12.2.jar                                                    | None                                     |
       | LCHIJA | supermartijn642configlib  | 1.1.6              | API_supermartijn642configlib-1.1.7-forge-mc1.12.jar                                   | None                                     |
       | LCHIJA | supermartijn642corelib    | 1.1.12             | API_supermartijn642corelib-1.1.12-forge-mc1.12.jar                                    | None                                     |
       | LCHIJA | patchouli                 | 1.0-23.6           | API_UTILITY_Patchouli-1.0-23.6.jar                                                    | None                                     |
       | LCHIJA | potioncore                | 1.9_for_1.12.2     | API_UTILITY_PotionCore-1.9_for_1.12.2.jar                                             | None                                     |
       | LCHIJA | baubles                   | 1.5.2              | UTILITY_Baubles-1.12-1.5.2.jar                                                        | None                                     |
       | LCHIJA | baubleye                  | 1.3.3              | BUGFIX_ADDON_-Baubles-_Baubley-Elytra-v1.3.3-mc1.12.2.jar                             | None                                     |
       | LCHIJA | loliasm                   | 5.14               | BUGFIX_censoredasm5.14--API_!mixinbooter.jar                                          | None                                     |
       | LCHIJA | damagetilt                | 0.1.0              | BUGFIX_DamageTilt-1.12.2-0.1.0.jar                                                    | None                                     |
       | LCHIJA | foamfix                   | @VERSION@          | BUGFIX_foamfix-0.10.15-1.12.2.jar                                                     | None                                     |
       | LCHIJA | nmsot                     | 1.2.2-mc1.12.2     | BUGFIX_NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar                                        | None                                     |
       | LCHIJA | notsoessential            | 1.0.3              | BUGFIX_NotSoEssential-Forge-1.0.3.jar                                                 | None                                     |
       | LCHIJA | particleculling           | v1.4.1             | BUGFIX_particleculling-1.12.2-v1.4.1.jar                                              | None                                     |
       | LCHIJA | rlmixins                  | 1.2.12             | BUGFIX_RLMixins-1.2.12--API_!mixinbooter.jar                                          | None                                     |
       | LCHIJA | sledgehammer              | 1.12.2-2.0.23      | BUGFIX_Sledgehammer-1.12.2-2.0.23--API_sponge_not_included.jar                        | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
       | LCHIJA | botania_tweaks            | 1.9.1              | CORE_ADDON_-Botania-_botaniatweaks-1.9.1.jar                                          | None                                     |
       | LCHIJA | botania                   | r1.10-364          | CORE_Botania+r1.10-364.4.jar                                                          | None                                     |
       | LCHIJA | botanianeedsit            | 1.12.2-3.0-release | CORE_ADDON_-Botania-_botanianeedsit-1.12.2-3.0-release.jar                            | None                                     |
       | LCHIJA | botanicadds               | 12.2.6             | CORE_ADDON_-Botania-_BotanicAdditions-1.12.2-12.2.6--API_HammerLib.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | ebwizardry                | 4.3.11             | CORE_ElectroblobsWizardry-4.3.11.jar                                                  | None                                     |
       | LCHIJA | arcane_essentials         | 1.0                | CORE_ADDON_-EW-_arcane_essentials-1.0.1.jar                                           | None                                     |
       | LCHIJA | mana_wizardry             | 0.3                | CORE_ADDON_-EW-Botania-_Mana+Wizardry-0.3.jar                                         | None                                     |
       | LCHIJA | grimoireofgaia            | 1.7.2              | CORE_GrimoireOfGaia3-1.12.2-1.7.2.jar                                                 | None                                     |
       | LCHIJA | arte_magicum              | 1.4.1              | CORE_ADDON_-EW-GOG3-_ArteMagicum-1.4.1--API_PotionCore.jar                            | None                                     |
       | LCHIJA | aether_legacy             | 1.5.3.2            | CORE_aether-1.12.2-v1.5.3.2.jar                                                       | None                                     |
       | LCHIJA | aquaculture               | 1.6.8              | CORE_Aquaculture-1.12.2-1.6.8.jar                                                     | None                                     |
       | LCHIJA | roots                     | @VERSION@          | NORMAL_ADDON_-mysticalworld-_Roots-1.12.2-3.1.7--API_mysticallib.jar                  | None                                     |
       | LCHIJA | treasure2                 | 2.2.0              | NORMAL_Treasure2-mc1.12.2-f14.23.5.2859-v2.2.0--API_GottschCore.jar                   | None                                     |
       | LCHIJA | treasure2_wizardry_lp     | 2.0.0              | NORMAL_ADDON_Treasure2WizardryLP-mc1.12.2-f14.23.5.2859-v2.0.0.jar                    | None                                     |
       | LCHIJA | astikorcarts              | 1.12.2-0.1.2.8     | NORMAL_astikorcarts-1.12.2-0.1.2.8.jar                                                | None                                     |
       | LCHIJA | basketcase                | 2.1.109            | NORMAL_basketcase-v2.1.109-mc1.12.2--API_primallib.jar                                | None                                     |
       | LCHIJA | bettercrates              | 1.2.0              | NORMAL_BetterCrates-1.2.0.jar                                                         | None                                     |
       | LCHIJA | ceramics                  | 1.12-1.3.7b        | NORMAL_Ceramics-1.12-1.3.7b.jar                                                       | None                                     |
       | LCHIJA | comforts                  | 1.4.1.3            | NORMAL_comforts-1.12.2-1.4.1.3.jar                                                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | enderbags                 | 2.1.0              | NORMAL_Ender+Bags-1.12.2-2.1.0--API_Placebo.jar                                       | None                                     |
       | LCHIJA | golems                    | 7.1.9              | NORMAL_ExtraGolems-1.12-7.1.9.jar                                                     | None                                     |
       | LCHIJA | cfm                       | 6.3.0              | NORMAL_furniture-6.3.2-1.12.2.jar                                                     | None                                     |
       | LCHIJA | dynamictrees              | 1.12.2-0.9.29      | UTILITY_DynamicTrees-1.12.2-0.9.29.jar                                                | None                                     |
       | LCHIJA | rustic                    | 1.1.7              | NORMAL_rustic-1.1.7.jar                                                               | None                                     |
       | LCHIJA | growthcraft               | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_fishtrap      | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_apples        | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_cellar        | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_grapes        | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_bamboo        | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_bees          | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_rice          | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_hops          | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | growthcraft_milk          | 4.2.2              | NORMAL_growthcraft-1.12.2-4.2.2.1.jar                                                 | None                                     |
       | LCHIJA | hole_filler_mod           | 1.0                | NORMAL_hole_filler_mod-1.2.4.1-mc_1.12.2-forge.jar                                    | None                                     |
       | LCHIJA | itemcollectors            | 1.1.8              | NORMAL_itemcollectors-1.1.8-forge-mc1.12--API_supermartijn642_x2.jar                  | None                                     |
       | LCHIJA | mysticalworld             | 1.12.2-1.11.0      | NORMAL_mysticalworld-1.12.2-1.11.0--API_mysticallib.jar                               | None                                     |
       | LCHIJA | qualitytools              | 1.0.7_for_1.12.2   | NORMAL_QualityTools-1.0.7_for_1.12.2--API_potioncraft.jar                             | None                                     |
       | LCHIJA | travelersbackpack         | 1.0.35             | NORMAL_TravelersBackpack-1.12.2-1.0.35.jar                                            | None                                     |
       | LCHIJA | waystones                 | 4.1.0              | NORMAL_Waystones_1.12.2-4.1.0.jar                                                     | None                                     |
       | LCHIJA | jeiintegration            | 1.6.0              | UTILITY_ADDON_-JEI-_jeiintegration_1.12.2-1.6.0.jar                                   | None                                     |
       | LCHIJA | jeivillagers              | 1.0                | UTILITY_ADDON_-JEI-_jeivillagers-1.12-1.0.2.jar                                       | None                                     |
       | LCHIJA | dynamictreesmysticalworld | 1.12.2-1.0.1       | UTILITY_ADDON_-MysticalWorld-DynamicTrees-_DynamicTreesMysticalWorld-1.12.2-1.0.1.jar | None                                     |
       | LCHIJA | quarkoddities             | 1                  | UTILITY_ADDON_-Quark-_QuarkOddities-1.12.2.jar                                        | None                                     |
       | LCHIJA | dynamictreesquark         | 1.12.2-1.0.6       | UTILITY_ADDON_-Quark-DynamicTrees-_DynamicTreesQuark-1.12.2-1.0.6.jar                 | None                                     |
       | LCHIJA | carryon                   | 1.12.3             | UTILITY_carryon-1.12.2-1.12.7.23.jar                                                  | None                                     |
       | LCHIJA | ctgui                     | 1.0.0              | UTILITY_CraftTweaker2-1.12-4.1.20.674.jar                                             | None                                     |
       | LCHIJA | crafttweakerjei           | 2.0.3              | UTILITY_CraftTweaker2-1.12-4.1.20.674.jar                                             | None                                     |
       | LCHIJA | orelib                    | 3.6.0.1            | API_OreLib-1.12.2-3.6.0.1.jar                                                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                 | 3.6.1.0            | UTILITY_DynamicSurroundings-1.12.2-3.6.1.0--API_OreLib.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | firespreadtweaks          | 1.1                | UTILITY_firespreadtweaks_1.12.2-1.1--API_collective.jar                               | None                                     |
       | LCHIJA | followingvillagers        | 1.0.1              | UTILITY_Following+Villagers-1.0.1.jar                                                 | None                                     |
       | LCHIJA | friendly_chests           | 1.0.3              | UTILITY_Friendly-Chests-v1.0.3-mc1.12.2--API_Fluidlogged-API.jar                      | None                                     |
       | LCHIJA | journeymap                | 1.12.2-5.7.1       | UTILITY_journeymap-1.12.2-5.7.1.jar                                                   | None                                     |
       | LCHIJA | neat                      | 1.4-17             | UTILITY_Neat+1.4-17.jar                                                               | None                                     |
       | LCHIJA | rbp                       | 2.1.2              | UTILITY_RealisticBlockPhysics-1.12.2-2.1.2.jar                                        | None                                     |
       | LCHIJA | theoneprobe               | 1.4.28             | UTILITY_theoneprobe-1.12-1.4.28.jar                                                   | None                                     |
       | LCHIJA | villagermarket            | 1.0.4              | UTILITY_villager-market-nbt-fix-1.12.2-1.0.4.jar                                      | None                                     |
       | LCHIJA | villagermarkers           | 1.0.5              | UTILITY_villagermarkers-1.12.2-1.0.5.jar                                              | None                                     |
       | LCHIJA | villagersleashed          | 1.0.0              | UTILITY_VillagersLeashable-1.0.jar                                                    | None                                     |
       | LCHIJA | wizardryutils             | 1.12.2-1.1.4       | API_WizardryUtils-1.12.2-1.1.4.jar                                                    | None                                     |
       | LCHIJA | wizardrygolems            | 1.12.2-1.2.0       | CORE_ADDON_-EW-ExtraGolems-_WizardryGolems-1.12.2-1.2.0--API_WizardryUtils.jar        | None                                     |
       | LCHIJA | spellbundle               | 1.12.2-1.1.4       | CORE_ADDON_-EW-_SpellBundle-1.12.2-1.1.4--API_WizardryUtils.jar                       | None                                     |
       | LCHIJA | gogredux                  | 1.0.0              | CORE_ADDON_-GOG3-_gogredux-1.12.2-1.0.0.jar                                           | None                                     |
       | LCHIJA | minefantasyreforged       | 1.12.2-0.2.9       | CORE_MineFantasyReforged-1.12.2-0.2.9.jar                                             | None                                     |
       | LCHIJA | betterdisplays            | 1.12.2-1.1.1       | NORMAL_BetterDisplays-1.12.2-1.1.1.jar                                                | None                                     |
       | LCHIJA | ironagefurniture          | 0.2.0.5            | NORMAL_ironagefurniture+1.12.2+v0.2.0.5.jar                                           | None                                     |
       | LCHIJA | dshuds                    | 3.6.0.0            | UTILITY_ADDON_-DynamicSurroundings-_DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | mysticallib               | 1.12.2-1.13.0      | API_mysticallib-1.12.2-1.13.0.jar                                                     | None                                     |
  Loaded coremods (and transformers): LoliASM (BUGFIX_censoredasm5.14--API_!mixinbooter.jar)
                                        
                                      RLMixinsPlugin (BUGFIX_RLMixins-1.2.12--API_!mixinbooter.jar)
                                        
                                      FMLPlugin (BUGFIX_NotSoEssential-Forge-1.0.3.jar)
                                        com.github.u9g.notsoessential.asm.ClassTransformer
                                      Baubley Elytra Plugin (BUGFIX_ADDON_-Baubles-_Baubley-Elytra-v1.3.3-mc1.12.2.jar)
                                        git.jbredwards.baubleye.BaubleyElytra$Transformer
                                      CreativePatchingLoader (API_CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      RandomPatches (BUGFIX_randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Friendly Chests Plugin (UTILITY_Friendly-Chests-v1.0.3-mc1.12.2--API_Fluidlogged-API.jar)
                                        git.jbredwards.friendly_chests.mod.asm.ASMHandler$Transformer
                                      HCASM (API_HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Born in a Barn (BUGFIX_BornInABarn1.8-1.12-1.2.jar)
                                        com.chocohead.biab.BornInABarn
                                      Botania Tweaks Core (CORE_ADDON_-Botania-_botaniatweaks-1.9.1.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      Quark Plugin (UTILITY_Quark-r1.6-179--API_AutoRegLib.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ClientFixer (BUGFIX_clientfixer-1.12.2-1.9--correct_fonts.jar)
                                        com.gamerforea.clientfixer.asm.ASMTransformer
                                      ParticleCullingLoadingPlugin (BUGFIX_particleculling-1.12.2-v1.4.1.jar)
                                        
                                      MixinBooter (API_!mixinbooter-8.3.jar)
                                        
                                      TransformLoader (UTILITY_DynamicSurroundings-1.12.2-3.6.1.0--API_OreLib.jar)
                                        
                                      SuperMartijn642's Core Lib Plugin (API_supermartijn642corelib-1.1.12-forge-mc1.12.jar)
                                        
                                      RandomPatches Integration (BUGFIX_ADDON_-randompatches-_rpintegration-1.12.2-1.5.1.0.jar)
                                        
                                      LoadingPlugin (BUGFIX_CrashToMainMenu-client-1.12.2-1.0.0.jar)
                                        com.wildbamaboy.crashtomainmenu.asm.ClassTransformer
                                      Fluidlogged API Plugin (API_Fluidlogged-API-v2.2.5-mc1.12.2.jar)
                                        git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerLevelProperty
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerSmoothWater
                                      ItemPatchingLoader (UTILITY_ItemPhysic_Full_1.4.37_mc1.12.2--API_CreativeCore.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (BUGFIX_foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.5.2.230523' Renderer: 'AMD Radeon RX 6600 XT'
  HammerCore Debug Information: Dependent Mods:
                                -Botanic Additions (botanicadds) @ 12.2.6
  Patchouli open book context: n/a
  Suspected Mods: Forge Mod Loader (FML), Minecraft Forge (forge), Dynamic Trees (dynamictrees)
  Launched Version: Forge 1.12.2
  LWJGL: 2.9.4
  OpenGL: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
```

### Reproducability

Just add it to mods. As I see it even didn't create it config

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://github.com/someaddons/performant_issues/files/12271012/latest.log

**Comment by cajlo** [comment]
I've chosen 1.16 because 1.12 wasn't here, sorry if it is discontinued, didn't find any information about it

**Comment by someaddons** [comment]
1.12 is not supported anymore^^

**Comment by shithubsucks** [comment]
but what does [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] 
even mean? That error shows up with a lot of modpacks it seems, even when they work fine and don't crash.
