### ISSUE TITLE
Instant Crash on Valhasia 3

### ISSUE THREAD

**Issue by OhNine** [someaddons/performant_issues#55]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

Instant crash of Valhasia 3

**To Reproduce**
1. load Valhasia 3 with Preformant
2. crash

** Mod version **
Performant-1.16.2-4-3.25m
Valhasia 3.1.1

**Log**
[18:12:00] [main/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod apothasm/container-repair.js function apothanvilcontainer
java.lang.NullPointerException: null
        at org.objectweb.asm.tree.InsnList.set(InsnList.java:194) ~[asm-tree-7.2.jar:7.2] {}
        at jdk.nashorn.internal.scripts.Script$Recompilation$219$363A$\^eval\_.initializeCoreMod#transformer(<eval>:48) ~[?:?] {re:classloading}
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?] {}
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?] {}
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?] {}
        at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-3.0.0.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-3.0.0.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-3.0.0.jar:?] {}
        at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:110) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) ~[modlauncher-8.0.6.jar:?] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:214) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:202) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:646) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.6.jar:8.0.6+85+master.325de55] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.13.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.13.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.13.jar:?] {}

**Comment by someaddons** [comment]
post the full log into a https://gist.github.com/

**Comment by tofran** [comment]
I also have the exact same problem:
[Here's my log](https://gist.github.com/tofran/edaea088dc6381b592ba1eacb0ef1e1c)

**Comment by OhNine** [comment]
https://gist.github.com/OhNine/698b5b5fb129dafa5862b5c5f3c455ae

**Comment by jcweaver997** [comment]
This also happens on the All the Mods 6 modpack, looks like something to do with sponge, but I'm not a modder so I don't know.
gist for ATM6 https://gist.github.com/jcweaver997/c8e078f6fec1026f1cc101ac1bc1c48c

**Comment by OhNine** [comment]
ok so i updated random patches but it seems like I am still getting a Null Pointer exception 
https://gist.github.com/OhNine/532b8035c95dcf1f1f00d98a0fa6c628

**Comment by jcweaver997** [comment]
Make sure your Random Patches version is the beta 2.0.1. The latest release 1.16.4-1.22.1.11 doesn't work

**Comment by OhNine** [comment]
it works now thank you all for your help
