### ISSUE TITLE
Java single player client closes before getting to main menu - only with version performant-1.16.2-4-3.25m, v3.24m works.

### ISSUE THREAD

**Issue by Atlntssplayer** [someaddons/performant_issues#58]
When I start the Java Minecraft client (version 1.16.4 with Forge 35.1.13) it closes after a few seconds.
This happens only with "performant-1.16.2-4-3.25m.jar" installed, not without it or with the previous version (performant-1.16.2-4-3.24m).

1. Launch the game
2. Wait a few seconds
3. See messages of "Completed deep scan of...." and some mod file names.
4. Client closes.

**Expected behavior**
Expected behavior is that the client doesn't close but gets into the main menu and I can load my save or start a new game.

** Mod version **
performant-1.16.2-4-3.25m.jar
Previous version of Performant (performant-1.16.2-4-3.24m.jar) I tried worked without appearant errors.

latest.log:

[26Dec2020 11:09:20.526] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_271 by Oracle Corporation
[26Dec2020 11:09:21.174] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[26Dec2020 11:09:21.216] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/user/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[26Dec2020 11:09:23.590] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '/'
[26Dec2020 11:09:23.590] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:1 token recognition error at: '/'
[26Dec2020 11:09:25.439] [main/ERROR] [mixin/]: Mixin config totaldarkness.mixins.json does not specify "minVersion" property
[26Dec2020 11:09:25.573] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[26Dec2020 11:09:25.576] [main/ERROR] [mixin/CATCHING]: Catching
java.lang.ClassNotFoundException: de.maxhenkel.shulkerbox.MixinConnector
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.6.jar:?]
	at java.util.HashMap.forEach(Unknown Source) [?:1.8.0_271]
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?]
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
		at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
		at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.6.jar:?]
		at java.util.HashMap.forEach(Unknown Source) [?:1.8.0_271]
		at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
[26Dec2020 11:09:25.602] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[26Dec2020 11:09:25.612] [main/INFO] [Portal/]: Invoking Mixin Connector
[26Dec2020 11:09:25.617] [main/ERROR] [mixin/]: Mixin config imm_ptl_mixins.json does not specify "minVersion" property
[26Dec2020 11:09:25.619] [main/ERROR] [mixin/]: Mixin config imm_ptl_mixins_forge.json does not specify "minVersion" property
[26Dec2020 11:09:25.621] [main/ERROR] [mixin/]: Mixin config imm_ptl_peripheral_mixins.json does not specify "minVersion" property
[26Dec2020 11:09:25.634] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, Minecraft Launcher, --gameDir, C:\Users\user\AppData\Roaming\.minecraft, --assetsDir, C:\Users\user\AppData\Roaming\.minecraft\assets, --uuid, 05142a77a7409fb8a45b9c55f963586c, --username, Titanlauncher3950, --assetIndex, 1.16, --accessToken, ????????, --userType, offline, --versionType, release]
[26Dec2020 11:09:25.864] [main/INFO] [com.performant.coremod.Performant/]: Performant configs loaded
[26Dec2020 11:09:27.396] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in imm_ptl_mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[26Dec2020 11:09:27.989] [main/WARN] [mixin/]: @Mixin target net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$ChunkRender$ChunkRenderTask is public in imm_ptl_mixins_forge.json:client.MixinChunkRenderTask and should be specified in value
[26Dec2020 11:09:27.996] [main/WARN] [mixin/]: @Mixin target net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$ChunkRender$RebuildTask is public in imm_ptl_mixins_forge.json:client.MixinRebuildTask and should be specified in value
[26Dec2020 11:09:28.327] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in performant.mixins.json:world.chunk.ChunkManagerEntityTrackMixin and should be specified in value
[26Dec2020 11:09:35.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[26Dec2020 11:09:35.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[26Dec2020 11:09:35.132] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[26Dec2020 11:09:35.132] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[26Dec2020 11:09:35.134] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[26Dec2020 11:09:35.135] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
[26Dec2020 11:09:35.136] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:149)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:46)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:41)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_210048_b(SourceFile:72)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_199194_a(SourceFile:21)
[26Dec2020 11:09:35.137] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.<clinit>(SourceFile:89)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.fixes.ChunkPaletteFormat.<clinit>(SourceFile:50)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.DataFixesManager.func_210891_a(SourceFile:349)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(SourceFile:207)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.datafix.DataFixesManager.<clinit>(SourceFile:203)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.Util.func_240990_b_(SourceFile:200)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.Util.func_240976_a_(SourceFile:193)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityType$Builder.func_206830_a(EntityType.java:657)
[26Dec2020 11:09:35.138] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityType.func_200712_a(EntityType.java:280)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:148)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$2(WorldGenRegistries.java:39)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.LinkedHashMap.forEach(Unknown Source)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[26Dec2020 11:09:35.139] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[26Dec2020 11:09:35.140] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Thread.run(Unknown Source)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method befOreComparetest(Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in performant.mixins.json:item.CompoundNBTMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap performant.refmap.json
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[26Dec2020 11:09:35.141] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[26Dec2020 11:09:35.142] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[26Dec2020 11:09:35.142] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[26Dec2020 11:09:35.142] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 40 more

**Comment by Atlntssplayer** [comment]
Thank you for this mod by the way!

**Comment by lucasvanhalst** [comment]
Server also crashes after a few seconds, so it's not limitted to the single player client

**Comment by ArchieBeepBoop** [comment]
Same issue, seems to be a mixin incompatibility?

**Comment by doctor-something5000** [comment]
If you have random patches installed this is a conflict problem.
install the latest 2.0+ of random patches to overcome this problem.

**Comment by ArchieBeepBoop** [comment]
> If you have random patches installed this is a conflict problem.
> install the latest 2.0+ of random patches to overcome this problem.

That does not seem to be the case. I have the latest version of random patches installed (the one compiled on the 15th of december) and this issue still happens.

**Comment by someaddons** [comment]
or disable the fastItemCompare in performants config
