### ISSUE TITLE
Fix mixin related issues

### ISSUE THREAD

**Issue by FrannDzs** [someaddons/performant_issues#89]
When I install performant I get 2 errors related to mixin

**To Reproduce**
1. Install Minecraft 1.16.4
2. Install Forge 35.1.36
3. Install performant-1.16.2-4-3.30m.jar

**Expected behavior**
Fix mixin related issues

** Mod version **
Forge 35.1.36

** Logs **
Latest/Crash log
[10ene2021 17:14:04.881] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, FrannDzs, --version, HMCL 3.3.179, --gameDir, C:\Users\Franco\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Franco\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, 72a6a693156b4d46861862888ce18584, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.179, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.36, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[10ene2021 17:14:04.955] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_272 by GraalVM Community
[10ene2021 17:14:06.332] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10ene2021 17:14:06.638] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Franco/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[10ene2021 17:14:13.289] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[10ene2021 17:14:13.302] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, HMCL 3.3.179, --gameDir, C:\Users\Franco\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Franco\AppData\Roaming\.minecraft\assets, --uuid, 72a6a693156b4d46861862888ce18584, --username, FrannDzs, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.179, --width, 854, --height, 480]
[10ene2021 17:14:13.512] [main/INFO] [com.performant.coremod.Performant/]: Performant configs loaded
[10ene2021 17:14:14.735] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[10ene2021 17:14:14.848] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[10ene2021 17:14:15.841] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in performant.mixins.json:world.chunk.ChunkManagerEntityTrackMixin and should be specified in value
[10ene2021 17:14:43.255] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://littleskin.cn/api/yggdrasil/authserver', accountsHost='http://127.0.0.1:12759/https/api.mojang.com', sessionHost='http://127.0.0.1:12759/https/sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10ene2021 17:14:45.206] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationException: Unauthorized
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:119) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:94) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.Minecraft.func_244735_a(Minecraft.java:551) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:383) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
[10ene2021 17:14:45.274] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: FrannDzs
[10ene2021 17:14:47.019] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[10ene2021 17:14:53.409] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 35.1.36, for MC 1.16.4 with MCP 20201102.104115
[10ene2021 17:14:53.411] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v35.1.36 Initialized
[10ene2021 17:14:53.757] [modloading-worker-1/ERROR] [com.telepathicgrunt.blame.Blame/]: Blame 1.8.1 initialized
[10ene2021 17:14:55.122] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:<init>:52]: Log Path: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.log
[10ene2021 17:14:55.125] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] CustomSkinLoader 14.13-SNAPSHOT-199
[10ene2021 17:14:55.155] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] DataDir: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader
[10ene2021 17:14:55.157] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Operating System: Windows 10 (amd64) version 10.0
[10ene2021 17:14:55.163] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Java Version: 1.8.0_272, GraalVM Community
[10ene2021 17:14:55.190] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Java VM Version: OpenJDK 64-Bit Server VM GraalVM CE 21.1.0-dev (mixed mode), GraalVM Community
[10ene2021 17:14:55.282] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Minecraft: 1.16.4(1.16.4)
[10ene2021 17:14:55.287] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Config File: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.json
[10ene2021 17:14:55.302] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Try to load config.
[10ene2021 17:14:55.324] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Successfully load config.
[10ene2021 17:14:55.467] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] version : 14.13
[10ene2021 17:14:55.483] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableDynamicSkull : true
[10ene2021 17:14:55.496] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableTransparentSkin : true
[10ene2021 17:14:55.497] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceIgnoreHttpsCertificate : false
[10ene2021 17:14:55.499] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceLoadAllTextures : false
[10ene2021 17:14:55.500] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableCape : true
[10ene2021 17:14:55.501] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] threadPoolSize : 3
[10ene2021 17:14:55.502] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] retryTime : 1
[10ene2021 17:14:55.504] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] cacheExpiry : 30
[10ene2021 17:14:55.505] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceUpdateSkull : false
[10ene2021 17:14:55.506] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableLocalProfileCache : false
[10ene2021 17:14:55.507] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableCacheAutoClean : false
[10ene2021 17:14:55.508] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceDisableCache : false
[10ene2021 17:14:55.540] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] loadList : 7
[10ene2021 17:14:58.898] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[10ene2021 17:14:59.004] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[10ene2021 17:14:59.114] [Worker-Main-2/INFO] [net.minecraft.world.biome.Biome/]: Performant loaded, lag begone!
[10ene2021 17:14:59.188] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[10ene2021 17:15:00.168] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: AHEAD Current: 35.1.36 Target: null
[10ene2021 17:15:14.901] [modloading-worker-0/WARN] [mixin/]: @Final field field_187234_c:Ljava/util/Map; in performant.mixins.json:entity.EntityDataManagerMixin should be final
[10ene2021 17:15:18.861] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[10ene2021 17:15:18.864] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[10ene2021 17:15:19.952] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[10ene2021 17:15:20.054] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10ene2021 17:15:20.055] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10ene2021 17:15:20.058] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10ene2021 17:15:20.062] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10ene2021 17:15:20.066] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10ene2021 17:15:20.068] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10ene2021 17:15:22.596] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10ene2021 17:15:22.611] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10ene2021 17:15:22.614] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10ene2021 17:15:23.658] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient/]: Could not authorize you against Realms server: Invalid session id
[10ene2021 17:15:52.835] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by someaddons** [comment]
no issue here
